<nav>
			<ul class="nav nav-pills">
				<li role="presentation"><a href="./">Home</a></li>
				<li role="presentation"><a href="1st_2nd.php">1st-2nd Generations</a></li>
				<li role="presentation"><a href="3rd_4th.php">3rd-4th Generations</a></li>
				<li role="presentation"><a href="5th_7th.php">5th-7th Generations</a></li>
				<li role="presentation"><a href="colophon.php">Colophon</a></li>
			</ul>
		</nav>
