<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Welcome</a>
		</div>
			<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav">
				<li role="presentation"><a href="./">Home</a></li>
				<li role="presentation"><a href="1st_2nd.php">1st-2nd Generations</a></li>
				<li role="presentation"><a href="3rd_4th.php">3rd-4th Generations</a></li>
				<li role="presentation"><a href="5th_7th.php">5th-7th Generations</a></li>
				<li role="presentation"><a href="colophon.php">Colophon</a></li>
			</ul>
			

		</nav>
