<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="./">
						<img class="navbar-brand" src="images/logo.png" alt="Pokémon"><?php echo $parentTitle;?>
					</a>
				</div>
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="1st_2nd.php">1st-2nd</a></li>
						<li><a href="3rd_4th.php">3rd-4th</a></li>
						<li><a href="5th_7th.php">5th-7th</a></li>
						<li><a href="colophon.php">Colophon</a></li>
					</ul>
				</div>
			</div>
		</nav>
