<!doctype html>

<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/styles.css">
		<title><?php echo $currentTitle;?><?php echo $separator;?><?php echo $parentTitle;?></title>
	</head>

	<body>
	
	<div class="container">

		<header class="page-header">
			<h1><a href="./"><?php echo $parentTitle;?></a></h1>
		</header>
